sudo: false
language: node_js

node_js:
  - "lts/*"

os:
  - linux

after_success:
  - npm run build-travis
  - ./tools/download-binaries.sh v1.0.1

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
